services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - distilled-network

  nestjs:
    build:
      context: ./distilled-be
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./distilled-be/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./distilled-be:/app
      - /app/node_modules
    networks:
      - distilled-network

networks:
  distilled-network:
    driver: bridge

volumes:
  postgres: